### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by unix1984** [alexandrevicenzi/hexchat-emoji#4] opened 2021-04-22 09:47 UTC
Traceback (most recent call last):
   File "/home/unix/.config/hexchat/addons/emojis/emojis.py", line 3, in <module>
     from . import db
 ImportError: attempted relative import with no known parent package
 Error loading module /home/unix/.config/hexchat/addons/emojis/emojis.py

**Comment by alexandrevicenzi** [comment] 2021-04-22 10:06
As said before, I can't do anything about this if you don't give more information about your environment.

It works on Ubuntu and openSUSE. You need to install `hexchat-plugins-python3` or ensure that your hexchat is using Python 3 and not Python 2.

**Comment by unix1984** [comment] 2021-04-22 10:56
~ ❯❯❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal


~ ❯❯❯ sudo apt install hexchat-plugins-python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hexchat-plugins-python3


~ ❯❯❯ sudo apt install hexchat-python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hexchat-python3 is already the newest version (2.14.3-3).
hexchat-python3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Installed python versions: 
python2.7 
python3
python3.8


what other information do you need?

Thanks!

**Comment by alexandrevicenzi** [comment] 2021-04-22 11:35
I have the same version of Ubuntu and I can't reproduce this error in any way.

Are you using HexChat from Snap? How did you install Emojis library?

**Comment by alexandrevicenzi** [comment] 2021-04-22 11:42
The way I have installed in Ubuntu was `pip3 install emojis -t ~/.config/hexchat/addons`.

The folder looks like:

```bash
~/.config/hexchat/addons $ ls -la
total 20
drwx------ 4 alexandre alexandre 4096 abr 22 13:40 .
drwx------ 6 alexandre alexandre 4096 abr 15 01:18 ..
-rw-rw-r-- 1 alexandre alexandre 3919 abr 13 00:58 emoji.py
drwxrwxr-x 4 alexandre alexandre 4096 abr 22 13:40 emojis
drwxrwxr-x 2 alexandre alexandre 4096 abr 22 13:40 emojis-0.6.0.dist-info
```

Ensure that you have the latest Emojis, 0.6.0, and not some older version that is probably causing the issue.

**Comment by unix1984** [comment] 2021-04-22 11:45
Yes, 
~ ❯❯❯ history | grep pip
pip3 install emojis -t ~/.config/hexchat/addons --upgrade
pip3 install emojis -t ~/.config/hexchat/addons


~ ❯❯❯ ls -la .config/hexchat/addons/
total 16
drwx------ 1 unix unix  124 Apr 22 13:11 ./
drwx------ 1 unix unix  312 Apr 22 13:11 ../
drwxrwxr-x 1 unix unix   66 Apr 22 13:11 emojis/
drwxrwxr-x 1 unix unix   96 Apr 22 13:11 emojis-0.6.0.dist-info/
-rw-rw-r-- 1 unix unix  990 Apr  9 16:18 emoji-slack-fix.py
-rw-rw-r-- 1 unix unix 8988 Apr  9 16:27 youtube_title.py

~ ❯❯❯ ls -la .config/hexchat/addons/emojis/
total 8
drwxrwxr-x 1 unix unix   66 Apr 22 13:11 ./
drwx------ 1 unix unix  124 Apr 22 13:11 ../
drwxrwxr-x 1 unix unix   94 Apr 22 13:11 db/
-rw-rw-r-- 1 unix unix 2154 Apr 22 13:11 emojis.py
-rw-rw-r-- 1 unix unix  141 Apr 22 13:11 __init__.py
drwxrwxr-x 1 unix unix   88 Apr 22 13:11 __pycache__/


more information: https://paste.unix-comp-airnet.net/paste/CUWZnoxz#eh3UljIs8tkCA4cWNlsLN1Cb+9mOkFGxrgRp5sCGrSW

**Comment by alexandrevicenzi** [comment] 2021-04-22 12:02
I have no idea, and the error is not in the HexChat plugin, but most probably the Emojis library.

I need to have a better look and it and probably change something in there.

**Comment by csasalu** [comment] 2021-04-28 15:01
Similar error in RHEL

$ hexchat --version
hexchat 2.14.1


 Traceback (most recent call last):
   File "/home/user/.config/hexchat/addons/emojis/emojis/emojis.py", line 3, in <module>
     from . import db
 ImportError: cannot import name 'db'
 Error loading module /home/user/.config/hexchat/addons/emojis/emojis/emojis.py

**Comment by alexandrevicenzi** [comment] 2021-04-28 23:55
@csasalu can you reproduce on Fedora?

Also, the path should be `/home/user/.config/hexchat/addons/emojis/emojis.py` and not `/home/user/.config/hexchat/addons/emojis/emojis/emojis.py`

**Comment by alexandrevicenzi** [comment] 2021-04-29 00:24
@csasalu @unix1984 could you please try to install this version of emojis:

`pip3 install git+https://github.com/alexandrevicenzi/emojis@hexchat#egg=emojis-0.6.0 -t ~/.config/hexchat/addons`

It's not public on PyPI, if it works I'll publish, for now, download from git.

**Comment by csasalu** [comment] 2021-04-29 09:32
I get the below error with the above version of emojis in RHEL. I have not tried on fedora yet.

 Traceback (most recent call last):
   File "/home/user/.config/hexchat/addons/emojis/emojis.py", line 3, in <module>
     from .utils import get_emoji_aliases
 ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package
 Error loading module /home/user/.config/hexchat/addons/emojis/emojis.py

**Comment by alexandrevicenzi** [comment] 2021-04-29 09:35
@csasalu delete emojis from addons, install with with `sudo pip3 install -U emojis` and see if it will work.

There's a need to restart HexChat for this to take effect.

I have no idea why it does not work, I tried all sorts of things on Ubuntu and openSUSE, and it just works.

**Comment by alexandrevicenzi** [comment] 2021-04-29 09:49
I tested on Fedora 34, if I install emojis in the addons folder I get `ModuleNotFoundError: No module named 'emojis'` once I start HexChat.

If I install emojis as a global package (`sudo pip3 install -U emojis`) the plugin works on HexChat.

**Comment by csasalu** [comment] 2021-04-29 16:11
Tried on Fedora 33 by installing emojis as a global package. Restarted hexchat and tried typing /em . IRC did not respond.
I later tried loading emojis.py from it's default install location but got this error:

` Traceback (most recent call last):
   File "<init code for '_hexchat_embedded'>", line 152, in loadfile
   File "/usr/local/lib/python3.9/site-packages/emojis/emojis.py", line 3, in <module>
     from . import db
 ImportError: attempted relative import with no known parent package`

**Comment by alexandrevicenzi** [comment] 2021-04-29 18:36
@csasalu try installing the new version as global, 0.6.0 use relative imports, the "hexchat" version does not.

`sudo pip3 install git+https://github.com/alexandrevicenzi/emojis@hexchat#egg=emojis-0.6.0`

It seems to me that installing emojis in `addons` does not work in some cases, even in Ubuntu.
It also seems that relative imports (used in 0.6.0) also cause some errors, so I removed everything that I could in the hexchat version.

**Comment by unix1984** [comment] 2021-05-08 13:17
is there a solution already?

**Comment by alexandrevicenzi** [comment] 2021-05-09 19:41
> is there a solution already?

Read the last comment and try it, if it does not work, I won't fix anything anymore.

It works on all machines that I tried, it's clear to me that it's an issue somewhere else.

**Comment by unix1984** [comment] 2021-05-09 19:52
Thank you now works properly!

`emoji version 1.0 loaded.`

![48135p](https://user-images.githubusercontent.com/78550977/117585084-d4a35880-b110-11eb-8379-f425e30ab24c.png)

**Closed as completed** 2021-10-08 20:20 UTC
